function collate_summary_files(options)
    % Helper function that generates summary files for simulations
    % in one step. Goal is for this to parse all the simulations
    % at one time and then generate a series of summary files
    % to make subsequent figures

    arguments
        options.top_data_folder = [ ...
            "../sim_data/demonstrate_growth", ...
            "../sim_data/growth_rates", ...
            "../sim_data/scan", ...
            "../sim_data/scan_valve_and_myofilaments", ...
            "../sim_data/arteriolar_resistance"]
        options.summary_file_string = [ ...
            "../summaries/demonstrate_growth.xlsx", ...
            "../summaries/growth_rates.xlsx", ...
            "../summaries/scan.xlsx", ...
            "../summaries/scan_valve_and_myofilaments.xlsx", ...
            "../summaries/arteriolar_resistanc" + ...
            "e.xlsx"]
        options.setup_file_string = [ ...
            "../setup/setup_growth_rates.json", ...
            "../../simulations/test_21/setup/setup_scan_parameters.json", ...
            "../../simulations/test_21/setup/setup_scan_valve_and_myofilaments.json", ...
            "../../simulations/test_21/setup/setup_scan_arteriolar_resistance.json", ...
            "../../simulations/test_21/setup/setup_scan_thin_filament_length_and_titin.json"]
        options.experiment_mode = [ ...
            "multipliers", ...
            "multipliers", ...
            "perturbations", ...
            "perturbations", ...
            "perturbations"]
        options.multiplier_variables = { ...
            ["wall_volume"], ...
            ["master_rate"], ...
            [], ...
            [], ...
            [], ...
            ["a_regulatory_units_per_strand", "t_k_stiff", "t_sigma"]};
    end

    omv = options.multiplier_variables

    % Loop through combinations
    for i = 1 : numel(options.top_data_folder)

        if (i ~= 3)
            continue
        end


        create_single_summary_file( ...
            top_data_folder = options.top_data_folder(i), ...
            summary_file_string = options.summary_file_string(i), ...
            figure_zoom_folder = options.figure_zoom_folder(i), ...
            setup_file_string = options.setup_file_string(i), ...
            experiment_mode = options.experiment_mode(i), ...
            multiplier_variables = options.multiplier_variables(i))

    end




