function collate_summary_files(options)
    % Helper function that generates summary files for simulations
    % in one step. Goal is for this to parse all the simulations
    % at one time and then generate a series of summary files
    % to make subsequent figures

    arguments
        options.top_data_folder = [ ...
            "../sim_data/growth_rates", ...
            "../sim_data/scan", ...
            "../sim_data/scan_valve_and_myofilaments"]
        options.summary_file_string = [ ...
            "../summaries/growth_rates.xlsx", ...
            "../summaries/scan.xlsx", ...
            "../summaries/valve_and_myofilaments.xlsx"]
        options.setup_file_string = [ ...
            "../setup/setup_growth_rates.json", ...
            "../setup/setup_scan_parameters.json", ...
            "../setup/setup_scan_valve_and_myofilaments.json"]
        options.experiment_mode = [ ...
            "multipliers", ...
            "perturbations", ...
            "perturbations"]
        options.multiplier_variables = { ...
            ["master_rate"], ...
            [], ...
            [] };
    end

    % Loop through combinations
    for i = 1 : numel(options.top_data_folder)

        create_single_summary_file( ...
            top_data_folder = options.top_data_folder(i), ...
            summary_file_string = options.summary_file_string(i), ...
            figure_zoom_folder = options.figure_zoom_folder(i), ...
            setup_file_string = options.setup_file_string(i), ...
            experiment_mode = options.experiment_mode(i), ...
            multiplier_variables = options.multiplier_variables(i))
    end
