function figure_plot_timecourses(options)
% Plot simulation time-courses

arguments
    options.data_files = [ ...
        "../sim_data/demonstrate_growth/sim_output/1/sim_output.txt", ...
        "../sim_data/demonstrate_growth/sim_output/1/sim_output.txt", ...
        "../sim_data/scan/sim_output/366/sim_output.txt", ...
        "../sim_data/scan/sim_output/489/sim_output.txt", ...
        "../sim_data/scan/sim_output/489/sim_output.txt", ...
        "../sim_data/arteriolar_resistance/sim_output/6/sim_output.txt", ...
        "../sim_data/arteriolar_resistance/sim_output/6/sim_output.txt"]
    
    options.template_files = [
        "multi_x_templates/template_example_beats.json", ...
        "multi_x_templates/template_example_growth.json", ...
        "multi_x_templates/template_example_growth_mybpc_destabilize_myosin.json", ...
        "multi_x_templates/template_example_beats_av_leak.json", ...
        "multi_x_templates/template_example_growth_av_leak.json", ...
        "multi_x_templates/template_example_beats_arteriolar_dilation.json", ...
        "multi_x_templates/template_example_growth_arteriolar_dilation.json"]
    
    options.output_image_files = [
        "../figures/fig_example_beats", ...
        "../figures/fig_example_growth", ...
        "../figures/fig_example_growth_mybpc_destabilize_myosin", ...
        "../figures/fig_example_beats_av_leak", ...
        "../figures/fig_example_growth_av_leak", ...
        "../figures/fig_example_beats_arteriolar_dilation", ...
        "../figures/fig_example_growth_arteriolar_dilation"]
    
    options.envelope_no_of_bins = 50

    options.output_image_types = ["png", "svg"]

    options.data_filter = struct("column", "time", "type", "isfinite");

end

% Cycle through the files
for file_i = 1 : numel(options.data_files)

    if (file_i < 6) | (file_i > 6)
        continue
    end

    figure_multi_x( ...
        options.data_files(file_i), ...
        options.template_files(file_i), ...
        data_file_filters = options.data_filter, ...
        output_file_string = options.output_image_files(file_i), ...
        output_file_types = options.output_image_types, ...
        envelope_no_of_bins = options.envelope_no_of_bins);
end
