function figure_plot_timecourses(options)
% Plot simulation time-courses

arguments
    options.data_files = [ ...
        "../sim_data/demonstrate_growth/sim_output/1/sim_output.txt", ...
        "../sim_data/demonstrate_growth/sim_output/1/sim_output.txt", ...
        "../simulations/scan_parameters/sim_output/366/sim_output.txt", ...
        "../simulations/scan_parameters/sim_output/489/sim_output.txt", ...
        "../simulations/scan_parameters/sim_output/489/sim_output.txt", ...
        "../simulations/arteriolar_resistance/sim_output/4/sim_output.txt", ...
        "../simulations/arteriolar_resistance/sim_output/4/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/1/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/1/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/2/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/2/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/3/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/3/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/4/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/4/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/5/sim_output.txt", ...
        "../simulations/demonstrate_growth/sim_output/5/sim_output.txt", ...
        "../simulations/scan_parameters/sim_output/451/sim_output.txt", ...
        "../simulations/scan_parameters/sim_output/1/sim_output.txt", ...
        "../../simulations/test_21/sim_data/scan_valve_and_myofilaments/sim_output/2/sim_output.txt", ...
        "../../simulations/test_21/sim_data/scan_valve_and_myofilaments/sim_output/3/sim_output.txt", ...
        "../../simulations/test_21/sim_data/scan_valve_and_myofilaments/sim_output/4/sim_output.txt", ...
        "../../simulations/test_21/sim_data/scan_valve_and_myofilaments/sim_output/5/sim_output.txt", ...
        "../../simulations/test_21/sim_data/demonstrate_growth/sim_output/1/sim_output.txt", ...
        "../../simulations/test_21/sim_data/growth_rates/sim_output/7/sim_output.txt"]
    
    options.template_files = [
        "multi_x_templates/template_example_beats.json", ...
        "multi_x_templates/template_example_growth.json", ...
        "../multi_x_templates/template_example_growth_mybpc_destabilize_myosin.json", ...
        "../multi_x_templates/template_example_beats_av_leak.json", ...
        "../multi_x_templates/template_example_growth_av_leak.json", ...
        "../multi_x_templates/template_example_beats_arteriolar_dilation.json", ...
        "../multi_x_templates/template_example_growth_arteriolar_dilation.json", ...
        "../multi_x_templates/template_example_beats_2.json", ...
        "../multi_x_templates/template_example_growth_2.json", ...
        "../multi_x_templates/template_example_beats_2.json", ...
        "../multi_x_templates/template_example_growth_2.json", ...
        "../multi_x_templates/template_example_beats_2.json", ...
        "../multi_x_templates/template_example_growth_2.json", ...
        "../multi_x_templates/template_example_beats_2.json", ...
        "../multi_x_templates/template_example_growth_2.json", ...
        "../multi_x_templates/template_example_beats_2.json", ...
        "../multi_x_templates/template_example_growth_2.json", ...
        "../multi_x_templates/template_valve.json", ...
        "../multi_x_templates/template_valve.json", ...
        "../multi_x_templates/template_valve.json", ...
        "../multi_x_templates/template_valve.json", ...
        "../multi_x_templates/template_example_beats.json", ...
        "../multi_x_templates/template_example_growth.json"]
    
    options.output_image_files = [
        "../figures/fig_example_beats", ...
        "../figures/fig_example_growth", ...
        "../output/fig_example_growth_mybpc_destabilize_myosin", ...
        "../output/fig_example_beats_av_leak", ...
        "../output/fig_example_growth_av_leak", ...
        "../output/fig_example_beats_arteriolar_dilation", ...
        "../output/fig_example_growth_arteriolar_dilation", ...
        "../output/fig_example_beats_1", ...
        "../output/fig_example_growth_1", ...
        "../output/fig_example_beats_2", ...
        "../output/fig_example_growth_2", ...
        "../output/fig_example_beats_3", ...
        "../output/fig_example_growth_3", ...
        "../output/fig_example_beats_4", ...
        "../output/fig_example_growth_4", ...
         "../output/fig_example_beats_5", ...
        "../output/fig_example_growth_5", ...
        "../output/valve_3", ...
        "../output/valve_4", ...
        "../output/valve_5", ...
        "../output/fig_example_beats", ...
        "../output/fig_example_growth"]
    
    options.envelope_no_of_bins = 50

    options.output_image_types = ["png", "svg"]

    options.data_filter = struct("column", "time", "type", "isfinite");

end

% Cycle through the files
for file_i = 1 : numel(options.data_files)

    % if (file_i < 16) | (file_i > 16)
    %     continue
    % end
    if (file_i > 2)
        break
    end

    figure_multi_x( ...
        options.data_files(file_i), ...
        options.template_files(file_i), ...
        data_file_filters = options.data_filter, ...
        output_file_string = options.output_image_files(file_i), ...
        output_file_types = options.output_image_types, ...
        envelope_no_of_bins = options.envelope_no_of_bins);
end
