function figure_growth_rates(options)

arguments
    options.data_file_string = "../summaries/summary_growth_rates.xlsx"

    options.dimension_fields = ["vent_wall_thickness", ...
                                    "vent_chamber_radius"];

    options.y_scaling_factor = 1000;

    options.y_ticks = [0 12 ; 0 35];

    options.y_axis_labels = {
        {'Diastolic', 'wall','thickness', '(mm)'}, ...
        {'Diastolic', 'chamber','radius', '(mm)'}}

    options.y_label_offset = -0.35;

    options.output_image_file = "../figures/fig_growth_rates"
    options.output_image_types = ["png", "svg"];


end

d = readtable(options.data_file_string)
dn = d.Properties.VariableNames';

d = d(d.time > 1000, :)

subplots = layout_subplots( ...
            figure_width = 3.5, ...
            panels_high = 2, ...
            x_to_y_ratio = 2, ...
            padding_left = 1, ...
            padding_top = 0.2, ...
            padding_bottom = [0.1 0.7]);

g = d.multiplier_1

for i = 1 : 2
    subplot(subplots(i));
    y = options.y_scaling_factor * d.(options.dimension_fields(i));
    plot(log10(g), y, 'o-');

    improve_axes( ...
        x_axis_label = "Relative growth rate", ...
        x_ticks = [-2 0 1], ...
        x_tick_label_positions = [-2 -1 0 1], ...
        x_tick_labels = {'0.01', '0.1', '1', '10'}, ...
        x_label_offset = -0.4, ...
        y_ticks = options.y_ticks(i, :), ...
        y_tick_decimal_places = 0, ...
        x_axis_off = (isequal(i, 1)), ...
        y_axis_label = options.y_axis_labels{i});
end

% Output figure
if (~(options.output_image_file == ""))
    for out_i = 1 : numel(options.output_image_types)
        output_file_string = ...
                sprintf("%s.%s", ...
                    options.output_image_file, ...
                    options.output_image_types(out_i));
        
        disp(sprintf('Writing image to: %s', output_file_string));

        exportgraphics(gcf, ...
            output_file_string, ...
            Resolution = 1200, ...
            ContentType = "auto");
    end
end